version: '3'

tasks:
  default:
    cmds:
      - go build -o totalrecall ./cmd/totalrecall
  run:
    cmds:
      - go run ./cmd/totalrecall
  test:
    cmds:
      - go test ./...
  install:
    cmds:
      - go install ./cmd/totalrecall
