#!/bin/bash
# Test script to verify image prompt persistence functionality

echo "Testing image prompt persistence in totalrecall GUI..."
echo ""
echo "Test scenarios:"
echo ""
echo "1. Create card with custom prompt:"
echo "   - Enter 'котка' in Bulgarian field"
echo "   - Enter custom prompt: 'cute fluffy cat playing with yarn'"
echo "   - Generate the card"
echo "   - The prompt is automatically saved"
echo ""
echo "2. Navigate away and back:"
echo "   - Use navigation arrows to go to another word"
echo "   - Navigate back to 'котка'"
echo "   - The custom prompt should be restored"
echo ""
echo "3. Regenerate image:"
echo "   - Click 'Regenerate Image'"
echo "   - The saved prompt will be used automatically"
echo ""
echo "4. Edit and save prompt:"
echo "   - Modify the prompt text"
echo "   - Changes are saved automatically"
echo "   - Regenerate to see the new prompt in action"
echo ""
echo "Press Ctrl+C to exit when testing is complete."
echo ""

./totalrecall gui